<?php return array(
    'name'=>'Name of School',
    'logo'=>['/images/logo.png','/images/nccg.png'],
    'phone'=>'0711545466',
    'email'=>'info@micartech.co.ke',
    'box_no'=>'7436346',
    'post_code'=>'',
    'town'=>'Nairobi',
    'website'=>'micartech.co.ke',
    'facebook'=>'ogilogeorge',
    'twitter'=>'ogilogeorge',
    'youtube'=>'ogilogeorge',
    'linkedin'=>'ogilogeorge',
    'physical_address'=>'Umoja 2, Moi Drive',
    'employer'=>['Nairobi City County','Board of Governors'],
);
