<?php return array(
    'name' => env('APP_NAME', 'Name of School'),
    'adm_number_pattern' => env('ADM_NUMBER_PATTERN', 'Name of School'),
    'logo' => [
        // 'logo1' => '/img/nairobi-city-county-logo.png',
        'logo1' => '/logo.png',
        'logo2' => '/logo.png',
    ],
    'phone' => '0727444240',
    'email' => 'info@micartech.co.ke',
    'box_no' => '6546',
    'post_code' => '00300',
    'town' => 'Nairobi',
    'website' => 'micartech.co.ke',
    'facebook' => 'micartechltd',
    'twitter' => 'micartechltd',
    'youtube' => 'micartechltd',
    'linkedin' => 'micartechltd',
    'physical_address' => 'Umoja 2, Moi Drive',
);
