<?php return array(
    'name' => env('APP_NAME', 'Name of School'),
    'adm_number_pattern' => env('VTCIMS_ADM_NUMBER_PATTERN', '{course}/{id}/{year}'),
    'logo' => [
        // 'logo1' => env('VTCIMS_LOGO_1','/img/nairobi-city-county-logo.png'),
        'logo1' => env('VTCIMS_LOGO_1', '/logo.png'),
        'logo2' => env('VTCIMS_LOGO_2', '/logo.png'),
    ],
    'phone' => env('VTCIMS_PHONE'),
    'email' => env('VTCIMS_EMAIL'),
    'box_no' => ENV('VTCIMS_BOX_NO'),
    'post_code' => ENV('VTCIMS_POST_CODE'),
    'town' => ENV('VTCIMS_TOWN'),
    'website' => ENV('VTCIMS_WEBSITE'),
    'facebook' => ENV('VTCIMS_FACEBOOK'),
    'twitter' => ENV('VTCIMS_TWITTER'),
    'youtube' => ENV('VTCIMS_YOUTUBE'),
    'linkedin' => ENV('VTCIMS_LINKEDIN'),
    'physical_address' => ENV('VTCIMS_PHYSICAL_ADDRESS'),
);
